### ISSUE TITLE
Rails Upgrade

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/oral-history#18]
# Summary 

Upgrade Rails to later version.  

# Acceptance Criteria

- [ ] Update from Rails 5.17 to Rails 6.1

# Notes
https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html

Rails 6 requires Ruby 2.5.  Should be on 2.5.8 currently.  

Docker -> FROM phusion/passenger-ruby25:1.0.11

**Comment by aprilrieger** [comment]
There are several things you should be aware of when upgrading a Ruby on Rails app from version 5.1.7 to 6.1. Here are some important considerations:

Compatibility: Check if your gems, plugins, and libraries are compatible with Rails 6.1. You may need to update some of them to their latest versions to ensure compatibility.

Ruby version: Rails 6.1 requires Ruby 2.5.0 or later, so make sure your app is running on the required Ruby version.

Configuration changes: The configuration file structure has changed in Rails 6.1, so you need to update your config files accordingly.

Action Cable: In Rails 6.1, Action Cable has been rewritten and some API changes have been made. Make sure to review the Action Cable documentation for these changes.

Zeitwerk: Rails 6.1 uses Zeitwerk as the default autoloader instead of the classic autoloader. Zeitwerk is faster and more reliable, but it has some differences in behavior. Check out the Rails documentation for more information.

Asset pipeline: The Asset Pipeline has been removed in Rails 6.1, and replaced with Webpacker as the default JavaScript bundler. You may need to update your app's asset management configuration.

Database: Rails 6.1 introduces a new feature called multi-database support. You may need to make changes to your database configuration and migrations to accommodate this new feature.

Testing: Some changes to the testing framework have been made in Rails 6.1. For example, system tests now use headless Chrome or Firefox by default. Make sure to review the Rails testing documentation for these changes.

Security: Rails 6.1 includes security enhancements such as stricter CSRF protection and default HTTP-only cookies. Make sure to review the Rails security documentation for these changes.

Performance: Rails 6.1 includes performance improvements such as faster database query caching and reduced memory usage. You may want to take advantage of these improvements by updating your app's configuration.

Overall, upgrading from Rails 5.1.7 to 6.1 requires careful consideration and planning. It's important to review the Rails documentation and carefully test your app to ensure a smooth transition.

**Comment by aprilrieger** [comment]
![Image](https://user-images.githubusercontent.com/63515648/230661103-1985181a-312d-4901-bc58-a6154854cb1e.png)
