### ISSUE TITLE
[SPIKE] What would need to be done for a solr 8.11 upgrade

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/oral-history#22]
# Summary

Look into upgrade paths from solr 7.7 to 8.11.  This ticket should explore what needs to be done when updating including if there is any migration, if items will need to be reimported, and whether or not wave files will need to be remade.  (Please note, we would prefer not to remake the wave files as they are time consuming).  

# Acceptance Criteria

- [x] Ticket or tickets for the solr upgrade have been created. 

Related ticket created: https://github.com/scientist-softserv/oral-history/issues/25

**Comment by summer-cook** [comment]
I used ChatGPT for a first pass at this, and I think it did a pretty good job. I plan on checking the external resources to see if theres anything it missed but here is what it had so far:

Here are the steps you may need to follow to upgrade the Solr version used by this app:

1. Review the release notes for Solr 8.11 to identify any changes or deprecations that may impact the Oral History Rails app. Pay particular attention to changes related to schema, configuration files, and API changes.
2. Make a backup of your Solr indexes and configuration files before upgrading to ensure that you can revert back if necessary.
3. Install Solr 8.11 and configure it to work with the Oral History Rails app. This may involve updating your Solr configuration files to reflect any changes in the new version of Solr.
4. If there are any changes to the Solr schema or configuration files, you may need to update the Oral History Rails app to reflect these changes. This may involve updating the solr-ruby gem or making changes to the application code to reflect changes in the Solr API.
5. Depending on the changes in the Solr version, you may need to reindex your data with Solr 8.11. This will depend on how you originally indexed your data and whether the index format has changed in the new version of Solr.
6. Since the Oral History Rails app appears to be using Solr for text search, it is unlikely that any WAV files used by the app would need to be recreated as part of the Solr upgrade.

Overall, the process for upgrading the Solr version used by the Oral History Rails app will involve reviewing changes in Solr 8.11, updating the Solr configuration files and the solr-ruby gem, and potentially reindexing data with the new version of Solr.

Here are some external resources you can use to learn more about upgrading from Solr 7.7 to Solr 8.11:
- Solr 8.11 Release Notes: The Solr 8.11 release notes provide a detailed overview of all the changes and new features introduced in this version. You can find the release notes at this link: https://lucene.apache.org/solr/guide/8_11/solr-8.11-release-notes.html
- Solr Upgrade Guide: The Solr upgrade guide provides a step-by-step guide to upgrading Solr from one version to another. You can find the upgrade guide at this link: https://lucene.apache.org/solr/guide/8_11/upgrade.html
- Rails Solr Integration Guide: The Rails Solr Integration Guide provides a detailed overview of how to integrate Solr with a Rails application using the solr-ruby gem. You can find the guide at this link: https://github.com/sunspot/sunspot/wiki/Rails-with-Solr-Integration-Guide
- Solr Ruby Gem Documentation: The Solr Ruby Gem Documentation provides detailed documentation on how to use the solr-ruby gem to interact with Solr from a Ruby application. You can find the documentation at this link: https://github.com/sunspot/sunspot#solr-ruby
- Solr Schema API Documentation: The Solr Schema API documentation provides a detailed overview of the schema.xml file and how to use it to define the schema for your Solr index. You can find the documentation at this link: https://lucene.apache.org/solr/guide/8_11/schema-api.html

**Comment by summer-cook** [comment]
Other useful links:

**Solr 8.11 major changes:** https://solr.apache.org/guide/solr/latest/upgrade-notes/major-changes-in-solr-8.html

**Comment by summer-cook** [comment]
Related ticket created: https://github.com/scientist-softserv/oral-history/issues/25

**Comment by summer-cook** [comment]
## Things to note:

- the app uses rsolr ruby gem, and i'm not sure how to figure out which version of solr is used in rsolr: https://github.com/rsolr/rsolr
- it also uses solr_wrapper gem: https://github.com/cbeer/solr_wrapper

**Comment by crisr15** [comment]
@summer-cook Will the wave forms be deleted/need to be recreated when re reindex?  Where are those stored?

**Comment by summer-cook** [comment]
@crisr15 I didn't find anything in the docs that talked about wav files specifically. They most likely wouldn't need to be deleted, but reindexed along with everything else in the app. They have a specific [section in their readme](https://github.com/scientist-softserv/oral-history#development-notes) that says that creating the wav files is very time intensive
Not sure exactly where the wav files are stored, but I'm pretty sure they use an oai feed. One other thing to note is I spoke to Jeremy about how blacklight is reindexed and here is our convo:

![Image](https://user-images.githubusercontent.com/73361970/225962825-ec7e9398-44b7-4aa2-a3b2-a47057b0fcfa.png)

I also found this in the apache solr docs:


![Image](https://user-images.githubusercontent.com/73361970/225963340-d633f07e-3965-47c6-bd92-0d98bbde68ee.png)


Because there is not a blacklight equivalent to reindex like there is in spotlight, and oral history uses an oai feed, the way to reindex would be the same as however they got the files into solr in the first place, or potentially rerunning the oai feed. 

I don't know if something similar to harvard's `spotlight_oaipmh` gem might be useful here, or if they already have a process in place for reindexing.
